[tox]
envlist = py39, pre-commit, mypy, test, docs, build

[testenv:pre-commit]
description = execute pre-commit to fix code issues
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run pre-commit run --all-files


[testenv:mypy]
description = execute mypy
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run mypy --install-types --non-interactive fireREST


[testenv:test]
description = execute pytest suite
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run pytest --cov=fireREST --cov-report=term


[testenv:docs]
description = build documentation with mkdocs
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run mkdocs build --strict


[testenv:build]
description = build source distribution and wheel
skip_install = true
deps = build
commands =
    python -m build
