from fireREST.defaults import API_RELEASE_623
from fireREST.fmc import Resource


class Incident(Resource):
    NAMESPACE = 'tid'
    PATH = '/tid/incident/{uuid}'
    MINIMUM_VERSION_REQUIRED_CREATE = API_RELEASE_623
    MINIMUM_VERSION_REQUIRED_GET = API_RELEASE_623
    MINIMUM_VERSION_REQUIRED_UPDATE = API_RELEASE_623
    MINIMUM_VERSION_REQUIRED_DELETE = API_RELEASE_623
