from fireREST.defaults import API_RELEASE_740
from fireREST.fmc import Resource


class NatExemptRule(Resource):
    """Retrieves the VPN NatExempt Rules generated by the Site To Site VPN Topology for a device.

    **Tags:** Policy

    **Supported operations:** GET

    **Operation IDs:**

    - `getVPNNatExemptModel` (GET)
    """

    PATH = '/policy/natexemptrules/{uuid}'
    MINIMUM_VERSION_REQUIRED_GET = API_RELEASE_740
