from fireREST.defaults import API_RELEASE_640, API_RELEASE_720
from fireREST.fmc import Resource


class CertEnrollment(Resource):
    PATH = '/object/certenrollments/{uuid}'
    MINIMUM_VERSION_REQUIRED_GET = API_RELEASE_640
    MINIMUM_VERSION_REQUIRED_CREATE = API_RELEASE_720
    MINIMUM_VERSION_REQUIRED_UPDATE = API_RELEASE_720
    MINIMUM_VERSION_REQUIRED_DELETE = API_RELEASE_720
